//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurdyaevKursach.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Excursion
    {
        public int ExcursionId { get; set; }
        public string ExcursionName { get; set; }
        public decimal ExcursionPrice { get; set; }
        public string ExcursionPlace { get; set; }
        public int ExcursionBuroId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime ExcursionDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ExcurionBuro ExcurionBuro { get; set; }
    }
}
